### PR TITLE
fix and optimize prod build and load time (under a second)

### PR DESCRIPTION
**Pull request by yacc**
This PR is to optimize load time of Mob.land

done:
- fix webpack production build
- fix Salus settings
- minify css in prod

todo:
- optimize image (webpack plugins)

### CODE REVIEW

**Comment by yacc** [comment]
Done:
* move to importing images (to benefit from automatic webpack online feature)
* convert images to webp format
* updated webpack to load webp

Todo:
* add fallback for browsers that don't support webp
* add bundle compression
* fix a couple of error that show up in the console

**Comment by yacc** [comment]
Done:
- webpack supports development and production mode
- fix webpack template (double loading bundled files)
- fix express app, was loading the webpack template file instead of the bundled version (that gave access to all optimizations)
- handle compressed assets in express if present, fallback if not compressed
- optimized image sizes and compressed further
- refactored loading of investor and partner images to leverage webpack 
- testing with Chrome Lighthouse

Todo:
- deploy to staging or upload to S3 with Cloudfront, and test online
- compare old version and new version of the site
- maybe further optimize mobile

**Comment by yacc** [comment]
Done:
- optimize mp4 and mp4 loading
- optimize bundle size for production build
- removed unused fonts
- optimized favicon loading

Todo:
- none

This PR is ready for review and deployment. This branch has been running and been tested live for about a week.

**Comment by yacc** [comment]
Done:
- loading web optimized mp4 from static.mob.land cloudfront
- removed all un-optimized *.png and *.jpg that were not used
- fix mobile bug where video was looping and was getting displayed when going back to home

This PR is ready to be reviewed, merged and deployed.
It's been tested in production on Ohio1 at https://logizomechanophobia.mob.land/

**Review by sullof — APPROVED** [review]

**Pull request merged**
